name: 'fhirworx'
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["seeeduino_xiao_ble"]'
      shield: '["microdox_left","microdox_right"]'
      alphas: '["qwerty"]'
      nav: '["invertedt"]'
      clipboard: '["mac"]'
      layers: '["flip"]'
